image_types_ostree: correct dependency to wic-tools
Issue: LINCD-799

fix problem do_image_ostree failed with below error:
ERROR: The file /usr/lib64/x86_64-wrs-linux/9.2.0/crtbeginT.o is
installed by both libgcc and libgcc-initial, aborting
DEBUG: Python function extend_recipe_sysroot finished

This problem only occurred when rm_work is enabled.
do_image_ostree depends on wic-tools:do_build , with rm_work
enabled, do_build will depend on do_rm_work_all
which will make libgcc-initial: do_rm_work as a dependency,
and then depend on libgcc-initial: do_populate_sysroot,
this will make libgcc-initial and libgcc both in direct
dependency, so error occurred.

correct the dependency to fix the problem

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>
Signed-off-by: Jason Wessel <jason.wessel@windriver.com>