classes/image_types_ostree.bbclass: Adapt to potential psuedo changes
If we do adopt path filtering for pseudo, we may filter out ${DEPLOY_DIR}
as not needing to be tracked for "root" permissions. We do need to track
the data installed by do_image_ostree though, so add the temp directory this
recipe uses out of ${DEPLOY_DIR} and place it in WORKDIR.
...
error: Writing content object: fchownat: Operation not permitted
...

Issue: LINCD-3344
Issue: LINCD-3342

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>