image_types_ostree.bbclass: ostree commit requires a lock
The core repostiory commands all require an external lock because
there is an internal ostree resource error when you try to operate on
a repository from more than one task.  You will get an error like:

  error: Locking repo exclusive failed: Resource temporarily unavailable
  WARNING: exit code 1 from a shell command.

[ Issue: LINUXEXEC-5186 ]

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>