libsoup: use -std=gnu89 to aviod native package build failed on different server
Issue: LIN1019-2677

Environment: "CentOS Linux 7 (Core)" based server
Compile error: /usr/include/resolv.h:75:9: error: unknown type name ‘u_char’

libsoup-2.4-native build error only happened on some CentOS based
build server, this may cause by different versions of gcc.

This is a workaround when build with feature wr-ostree.

Signed-off-by: Liwei Song <liwei.song@windriver.com>