init-ostree-install.sh: fix local reinstall to non boot media failed
While reinstall from local ostree repo, if chose a non boot media
to install, ostree pull failed to get local ostree repo
...
running: ostree pull --repo=/sysroot/ostree/repo wrlinux wrlinux-image-small

error: /sysroot/boot/efi/ostree_repo: opendir(/sysroot/boot/efi/ostree_repo): No such file or directory
...

In first install, if the install media is the same to boot media, tha label
instboot will be changed, and local override ostree repo locates 1st partion
of boot media

In second install, if the install media is different than boot media, the label
instboot is not available, then mount $idev (which is set according to PUUID=XXX,
UUID=XXX,LABEL=XXX) to get local override ostree repo

Issue: LINCD-3413

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>